apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /app
      name: azure-volume
  volumes:
  - name: azure-volume
    persistentVolumeClaim:
      claimName: my-pvc
  